applications/persona/urls.py
from django.urls import path
from . import views


app_name = 'persona_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='Inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleado.as_view(),
        name = 'listar_empleado'
    ),
    path(
        'lista-by-area/<shorName>/', 
        views.ListByAreaEmpleado.as_view(),
        name= 'empleados_area'
        ),
    path("lista-by-trabajo/<job>/", views.ListByBojEmpleado.as_view()),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/<id>/", views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='registrar_empleado'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado',
    ),
    path(
        'lista-empleado-admin/',
        views.ListAllEmpleadoAdmin.as_view(),
        name = 'lista_empleado_admin'
    )
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Include apps departamento
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidades', max_length=50)
    # Empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleados'

    def __str__(self):
        return f'{self.id} - {self.habilidad}'
    

class Empleado (models.Model):
    # Modelo para tabla empleado

    # Contador
    # Administrador
    # Economista
    # Otro
    job_choices = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Gestor de Recursos Humanos'),
        ('4', 'Analista de Gerencia'),
        ('5', 'Otro'),
    )
    
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo',max_length=1, choices=job_choices)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', null= True, blank=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()
    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Listado de personas'
        ordering = ['first_name']
        unique_together = (
            'first_name',
            'last_name',
        )
      
    def __str__(self) -> str:
        return f'{self.id} - {self.first_name} - {self.last_name}'

applications/persona/forms.py
from django import forms
from django.forms import fields
from django.forms import widgets
from .models import Empleado
class EmpleadoForm(forms.ModelForm):
    pass
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
            'hoja_vida',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(

            ),
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
from .models import Empleado
from .forms import EmpleadoForm

# Create your views here.
class InicioView(TemplateView):
    template_name = 'inicio.html'
    

class ListAllEmpleado(ListView):
    template_name = 'persona/list_all.html'
    # model = Empleado
    paginate_by = 4
    ordering = '-id'
    def get_queryset(self):
        nombre_completo = self.request.GET.get('nombre_completo','')
        print(nombre_completo)
        lista = Empleado.objects.filter(
            full_name__icontains=nombre_completo
        )
        return lista


class ListAllEmpleadoAdmin(ListView):
    template_name = 'persona/lista_empleados_admin.html'
    paginate_by = 10
    ordering = '-id'
    context_object_name = 'empleados'
    model = Empleado


# Listar empleados por el area
class ListByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'
    def get_queryset(self):
        shor_name = self.kwargs['shorName']
        lista = Empleado.objects.filter (
            departamento__shor_name = shor_name
        )
        return lista


# Listar empleados por trabajo
class ListByBojEmpleado(ListView):
    template_name = 'persona/list_by_trabajo.html'
    model = Empleado
    def get_queryset(self):
        job = self.kwargs['job']
        job_id = -1
        for elemento in Empleado.job_choices:
            if elemento[1].lower().find(job.lower()) >= 0:
                job_id = elemento[0]

        lista = Empleado.objects.filter(
            job = job_id
        )
        return lista 


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        
        palabra_clave = self.request.GET.get('kword_xd_name','')
        print('**************************')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        print(lista)
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name ='habilidades'
    def get_queryset(self):
        id = self.kwargs['id']
        print(id)
        empleado = Empleado.objects.get(id=id)
        print(empleado)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    template_name = 'persona/detail_empleado.html'
    model = Empleado
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['texto'] = 'Este es el texto de detailView'
        return context


class SuccessView(TemplateView):
    template_name = 'persona/success.html'


class EmpleadoCreateView(CreateView):
    template_name = 'persona/add.html'
    
    form_class = EmpleadoForm

    success_url = reverse_lazy('persona_app:lista_empleado_admin')

    def form_valid(self, form):
        # Lógica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = f'{empleado.first_name} {empleado.last_name}'
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = 'persona/update.html'
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'hoja_vida',
    ]
    success_url = reverse_lazy('persona_app:lista_empleado_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('*****************METODO POST*****************')
        print('**********************************')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)


    def form_valid(self, form):
        print('*****************METODO FORM VALID*****************')
        print('**********************************')
        return super().form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'persona/delete.html'
    success_url = reverse_lazy('persona_app:correcto')

templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar empleado
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar persona</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            
            <div class="medium-6 cell">
                <label>Nombres
                    {{ form.first_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos
                    {{ form.last_name }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo
                    {{ form.job }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>departamento
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Avatar
                    {{ form.avatar }}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Hoja de Vida
                </label>
                {{ form.hoja_vida }}
            </div>
            <button type="submit" class="success button cell large-4">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}
    

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword_xd_id" name="kword_xd_name" placeholder="Ingrese la palabra clave">
    <button type="submit">Buscar</button>
</form>
<h3>Lista resultados</h3>
<ul>
    {% for empleado in empleados %}
        <li>{{ empleado }}</li>
    {% endfor %}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
   Eliminar empleado 
{% endblock title %}
    


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.full_name }}</h1>
        <div class="cell callout alert">
            <h5>¿Desea eliminar a este empleado?</h5>
            <form method="POST"> {% csrf_token %}
                <button type="submit" class="alert button">Continuar</button>
            </form>
        </div>
        
    </div>
</div>



{% endblock content %}
    

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    {{ empleado.full_name }}
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}


<div class="grid-container">
    <div class="grid-x align-center">
        <div class="card cell" style="width: 300px; margin-top: 50px;">
            <div class="card-divider">
                <h4>{{ object.get_job_display }}</h4>
            </div>
            
            {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
            {% else %}
            <img src="{% static 'img/sliderInicio/01.jpg' %}">
            {% endif %}
                
            <div class="card-section">
                <h4>{{empleado.full_name}}</h4>
                <p>{{empleado.first_name}}</p>
                <p>{{empleado.last_name}}</p>
                <p>{{empleado.departamento.name}}</p>
                <ul class="nested vertical menu">
                    <p><span class="label">Habilidades:</span></p>
                    {% for habilidad in empleado.habilidades.all %}
                    <li>
                        {{habilidad.habilidad}}
                    </li>
                    {% endfor %}
                    
                </ul>
            </div>
        </div>
    </div>
</div>



{% endblock content %}
    

templates/persona/habilidades.html
<h1>Lista de personas por habilidades</h1>
<ul>
    
    {% for elemento in habilidades %}
        <li>{{ elemento }}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-4">
                    <input type="text" name="nombre_completo" id="nombre_completo" placeholder="Ingrese empleado">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="button warning" href="#">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCIÓN</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for elemento in object_list %}
                            <tr>
                                <td>{{ elemento.id }}</td>
                                <td>{{ elemento.first_name }}</td>
                                <td>{{ elemento.last_name }}</td>
                                <td>{{ elemento.departamento }}</td>
                                <td><a class="button warning" href="{% url 'persona_app:detalle_empleado' elemento.id %}">Ver</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell">
                
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                            </li>
                        {% endif %}


                        {% for page_number in paginator.page_range %}
                        
                        {% ifequal page_obj.number page_number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{ page_number }}</li>
                        {% else %}
                        <li><a href="?page={{ page_number }}">{{page_number}}</a></li>
                        {% endifequal %}
                        
                        {% endfor %}

                        
                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                            
                        
                    </ul>
                  </nav>
                {% endif %}
                    
            </div>
        </div>
        
    </div>
    
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista empleados por departamento
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            Empleados por area
        </div>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCIÓN</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in empleados %}
                        <tr>
                            <td>{{ elemento.id }}</td>
                            <td>{{ elemento.first_name }}</td>
                            <td>{{ elemento.last_name }}</td>
                            <td>{{ elemento.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:detalle_empleado' elemento.id %}">Ver</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>






{% endblock content %}
    

templates/persona/list_by_trabajo.html
<h1>Lista de empleados por trabajo</h1>

<ul>
    
    {% for elemento in object_list %}
        <li>{{elemento}}</li>
    {% endfor %}
    
</ul>

templates/persona/lista_empleados_admin.html
{% extends 'base.html' %}


{% block title %}
    Lista empleados admin
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCIÓN</th>
                  </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento }}</td>
                            <td>
                                <a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button alert" href="{% url 'persona_app:eliminar_empleado' empleado.id %}">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                    {% endif %}


                    {% for page_number in paginator.page_range %}
                    
                    {% ifequal page_obj.number page_number %} 
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ page_number }}</li>
                    {% else %}
                    <li><a href="?page={{ page_number }}">{{page_number}}</a></li>
                    {% endifequal %}
                    
                    {% endfor %}

                    
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
                        
                    
                </ul>
              </nav>
            {% endif %}
                
        </div>
    </div>
    
</div>
{% endblock content %}
    
    

templates/persona/success.html
<h1>Felicitaciones se guardo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}



{% block title %}
    Editar empleado admin
{% endblock title %}
    

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <class class="grid-x">
            <h1 class="cell">Modificar datos del empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Nombres
                            {{form.first_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Apellidos
                            {{form.last_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Trabajo
                            {{form.job}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Departamento
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Habilidades
                            {{form.habilidades}}
                        </label>
                    </div>

                    <div class="medium-12 cell">
                        <label>Hoja de Vida
                        </label>
                        {{form.hoja_vida}}
                    </div>

                    <button type="submit" class="success button">Guardar</button>
                </form>
            </div>
        </class>
    </div>
    
{% endblock content %}
    