applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
    path(
        'lista-departamento/', 
        views.ListaDepartamentoListView.as_view(), 
        name='lista_departamento'
    )
]

applications/persona/urls.py
from django.urls import path
from . import views


app_name = 'persona_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='Inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleado.as_view(),
        name = 'listar_empleado'
    ),
    path(
        'lista-by-area/<shorName>/', 
        views.ListByAreaEmpleado.as_view(),
        name= 'empleados_area'
        ),
    path("lista-by-trabajo/<job>/", views.ListByBojEmpleado.as_view()),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/<id>/", views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='registrar_empleado'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado',
    ),
    path(
        'lista-empleado-admin/',
        views.ListAllEmpleadoAdmin.as_view(),
        name = 'lista_empleado_admin'
    )
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Include apps departamento
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:listar_empleado' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:lista_empleado_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:registrar_empleado' %}" class="button">Registrar Nuevo</a></li>
        </ul>
    </div>
</div>