applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
    path(
        'lista-departamento/', 
        views.ListaDepartamentoListView.as_view(), 
        name='lista_departamento'
    )
]

applications/persona/urls.py
from django.urls import path
from . import views


app_name = 'persona_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='Inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleado.as_view(),
        name = 'listar_empleado'
    ),
    path(
        'lista-by-area/<shorName>/', 
        views.ListByAreaEmpleado.as_view(),
        name= 'empleados_area'
        ),
    path("lista-by-trabajo/<job>/", views.ListByBojEmpleado.as_view()),
    path("buscar-empleado/", views.ListEmpleadosByKword.as_view()),
    path("listar-habilidades-empleado/<id>/", views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='registrar_empleado'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(), 
        name='eliminar_empleado',
    ),
    path(
        'lista-empleado-admin/',
        views.ListAllEmpleadoAdmin.as_view(),
        name = 'lista_empleado_admin'
    )
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Include apps departamento
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length = 50, blank=False)
    shor_name = models.CharField('Nombre corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return f'{self.id} - {self.name} - {self.shor_name}' 

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from applications.departamento.models import Departamento

class ListaDepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    context_object_name = 'departamentos'
    model = Departamento

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('Estamos en el form valid')

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        departamento = form.cleaned_data['departamento']
        shortname = form.cleaned_data['shortname']

        depa = Departamento(
            name = departamento,
            shor_name = shortname,
        )
        depa.save()

        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            full_name = f'{nombre} {apellidos}',
            job = '1',
            departamento = depa,
            hoja_vida = '123'
        )
        return super(NewDepartamentoView, self).form_valid(form)  

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a></td>
                        </tr>
                        {% endfor %}
                            
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Nuevo departamento</h1>
        <form class="grid-x callout cell grid-margin-x" method="POST"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos
                    {{ form.apellidos }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento
                    {{ form.departamento }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Short Name
                    {{ form.shortname }}
                </label>
            </div>
            <button type="submit" class="cell large-4 success button">Guardar</button>
        </form>
    </div>
</div>

{% endblock content %}
    